name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  ENVIRONMENT: QA
  LOG_LEVEL: INFO

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build Docker image
        run: |
          docker build --build-arg ENV=${{ env.ENVIRONMENT }} --build-arg LOG_LEVEL=${{ env.LOG_LEVEL }} \
            -t integration-tests .
      - name: Run Tests for JOKR Application
        run: |
          docker run --name integration-tests-container \
                  -e TAG=LOGIN -e PLATFORM=AND -e CLEAN_LOGS=True \
                  -e APPLICATION=JKR -e NOT_RUN=~MRK -e TAG_BUG=~BUG \
                    integration-tests
      - name: Clean Container
        run: |
          docker stop integration-tests-container
          docker rm integration-tests-container