name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=api-automation-framework" >> $GITHUB_ENV
      - name: Print working directory
        run: pwd
      - name: Run Behave Tests
        uses: cryptic-wizard/run-behave-tests@v0.4.0
        with:
          test-path: project
          test-output-name: results.txt
