name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.5
      - uses: cryptic-wizard/run-behave-tests@v0.4.0
        with:
          test-path: test
          test-output-name: results.txt
