name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: latest
      - name: Set up Python environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=project" >> $GITHUB_ENV
      - name: Run Behave Tests
        uses: cryptic-wizard/run-behave-tests@v0.4.0
        with:
          test-path: test
          test-output-name: results.txt
