name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Print working directory
        run: pwd
      - name: List files in the working directory
        run: ls -la
      - name: Set Environment Variables
        run: |
          echo "ENVIRONMENT=QA" >> $GITHUB_ENV
          echo "LOG_LEVEL=DEBUG" >> $GITHUB_ENV
      - name: Verify Environment Variables
        run: |
          echo $ENVIRONMENT
          echo $LOG_LEVEL
      - name: Build Docker image
        run: |
          docker build --build-arg ENV=${{ vars.ENVIRONMENT }} --build-arg LOG_LEVEL=${{ vars.LOG_LEVEL }} \
            -t integration-tests .
      - name: Run Tests for JOKR Application
        run: |
          docker run --rm --name integration-tests-container \
                  -e TAG=84147 -e PLATFORM=AND -e CLEAN_LOGS=True \
                  -e APPLICATION=JKR -e NOT_RUN=~MRK -e TAG_BUG=~BUG \
                    integration-tests